### ISSUE TITLE
Test's aren't passing == Bad Install?

### ISSUE THREAD

**Issue by gauntface** [UnionOfRAD/framework#47]
Again - apologies if this is the wrong place to post this.

I've just tried running all the tests for my lithium install I'm there are a couple of fatal errors and I'm just wondering how much of that is a bad environment vs it's a beta release and tests aren't there yet?

```
Fatal error: Uncaught Error: Cannot use object of type lithium\storage\session\adapter\Cookie as array in /<Site Directory>/server/libraries/lithium/storage/session/adapter/Cookie.php:163 Stack trace: #0 /<Site Directory>/server/libraries/lithium/tests/cases/storage/session/adapter/CookieTest.php(268): lithium\storage\session\adapter\Cookie->lithium\storage\session\adapter\{closure}(Object(lithium\storage\session\adapter\Cookie), Array, NULL) #1 /<Site Directory>/server/libraries/lithium/tests/cases/storage/session/adapter/CookieTest.php(268): Closure->__invoke(Object(lithium\storage\session\adapter\Cookie), Array, NULL) #2 /<Site Directory>/server/libraries/lithium/test/Unit.php(1613): lithium\tests\cases\storage\session\adapter\CookieTest->testNameWithDotCookie() #3 /<Site Directory>/server/libraries/lithium/aop/Filters.php(231): lithium\test\Unit->lithium\test\{closure}(Array) #4 /<Site Directory>/server/libraries/lithium/test/Unit.php(1617): lithium\aop\Filters::run(Object(lithium\tests\cases\storage\session\adapter\CookieTest), in /<Site Directory>/server/libraries/lithium/storage/session/adapter/Cookie.php on line 163
```

Problem code is:

```
$result = $cookie->write($key, $value)->__invoke($cookie, compact('key', 'value'), null);
$this->assertCookie(compact('key', 'value'));
```

**Comment by davidpersson** [comment]
This seems to be a problem with the tests in UnionOfRAD/lithium: 
https://github.com/UnionOfRAD/lithium/blob/1.1/tests/cases/storage/session/adapter/CookieTest.php

It'd be great if reopen this ticket over there. Thanks!

**Comment by davidpersson** [comment]
Fixed in https://github.com/UnionOfRAD/lithium/commit/938679b2fae89957cae85679310472864628e26b
